### ISSUE TITLE
Dataset unavailable

### ISSUE THREAD

**Issue by danlou** [OanaMariaCamburu/e-SNLI#1]
Hi,

This dataset seems really interesting, great work!

I'm looking forward to running some experiments on it, but it seems that it's still unavailable.

Do you think you can give us some idea about when it'll be made available?

Thanks!

**Comment by SawanKumar28** [comment]
Hi @OanaMariaCamburu, this is a great dataset. Do you have a timeline in mind for releasing the dataset?

**Comment by little1tow** [comment]
This is a very interesting dataset. I also want to know when it is available. Thanks

**Comment by Gitsamshi** [comment]
Great work, hope to see the dataset

**Comment by anirbanl** [comment]
Hi @OanaMariaCamburu. Great work! We are very interested in using the dataset. Please let us know how can I avail this.

**Comment by Herobring** [comment]
Hi @OanaMariaCamburu , your work looks promising, looking forward to reproduce your results once the dataset is available!

**Comment by OanaMariaCamburu** [comment]
The dataset is now uploaded, sorry for the delay! :)
