### ISSUE TITLE
Where is SICK_DIC_LABELS

### ISSUE THREAD

**Issue by MrZhengXin** [OanaMariaCamburu/e-SNLI#2]
https://github.com/OanaMariaCamburu/e-SNLI/blob/d15ff653060e9e0459c45f894b9b86f721642d4c/attention/eval_attention.py#L14

I'm wondering where could I find SICK_DIC_LABELS, since it's not in data_attention_bottom.

**Comment by OanaMariaCamburu** [comment]
Sorry, this import was not actually used in that version of code, I've removed it. Thanks!
