### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by vibhavagarwal5** [OanaMariaCamburu/e-SNLI#5]
Hi, can I get the config files used in the code to better understand the code? There are a few places where it's being used, so just to get a better idea of the flow, config file might be great.

**Comment by vibhavagarwal5** [comment]
@OanaMariaCamburu Can you share the exact argparse arguments that you passed for the training. I'm trying to get the same numbers as the paper.

**Comment by OanaMariaCamburu** [comment]
Sorry for the delay. Please find them in each of the directories of the two models. The first line are the args passed by hand at cmd line and the second is the full set of args, normally they should be the defaults of what's in the main file.

**Comment by vibhavagarwal5** [comment]
Thanks for the update. Just a small correction in `seq_seq/config.txt` file. It should be `--not_use_diff_prod_sent_embed` instead of `--use_diff_prod_sent_embed` in the first line. Right?

**Comment by OanaMariaCamburu** [comment]
Sorry for the confusion. I have modified (to what I thought it was only a bit, for the form) the files between the time I used it to obtain the uploaded trained models that gave the published results and the time I uploaded the files online. The config I gave you was from a log file taken from the model uploaded, so please use the logics from there, it *not*_use_diff_prod_sent_embed, i.e., --use_diff_prod_sent_embed should remain False.
