### ISSUE TITLE
Difference between Sentence_highlighted_1 vs Sentence_marked_1

### ISSUE THREAD

**Issue by zhaoxy92** [OanaMariaCamburu/e-SNLI#6]
Hi,

Thanks for the work!
Could you please explain what does "Sentence_Highlighted_1" and "Sentence_marked_1" mean in the datasets? Thank you!

**Comment by OanaMariaCamburu** [comment]
Hi! Sorry for the confusion:

Sentence1_marked_1: is the premise (Sentence2 for hypothesis) were words between start (*) were highlighted by the workers.
Sentence1_Highlighted_1: is the list of indices of the highlighted words, where the index starts at 0 and the organization is only done by splitting with space

Hope this helps!
